# Generated by Django 5.2 on 2025-06-07 07:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='订单项ID')),
                ('dish_name', models.CharField(max_length=100, verbose_name='菜品名称（快照）')),
                ('dish_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='菜品单价（快照）')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='购买数量')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='小计金额')),
                ('dish_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='菜品图片（快照）')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='特殊要求')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单项',
                'verbose_name_plural': '订单项',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='订单总金额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='优惠金额')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='实付金额')),
                ('status', models.CharField(choices=[('pending_payment', '待支付'), ('paid', '已支付'), ('preparing', '制作中'), ('ready', '待取餐'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending_payment', max_length=20, verbose_name='订单状态')),
                ('payment_status', models.CharField(choices=[('unpaid', '未支付'), ('paid', '已支付'), ('refunded', '已退款'), ('partial_refunded', '部分退款')], default='unpaid', max_length=20, verbose_name='支付状态')),
                ('table_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='桌号')),
                ('customer_notes', models.TextField(blank=True, null=True, verbose_name='顾客备注')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='管理员备注')),
                ('estimated_time', models.IntegerField(blank=True, null=True, verbose_name='预估完成时间（分钟）')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('paid_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancelled_time', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon', verbose_name='使用的优惠券')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_time'],
            },
        ),
    ]
