# Generated by Django 5.2 on 2025-06-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='餐厅名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='餐厅描述')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='餐厅地址')),
                ('business_hours', models.JSONField(blank=True, null=True, verbose_name='营业时间')),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='餐厅LOGO')),
                ('background_images', models.JSONField(blank=True, null=True, verbose_name='背景图片URLs')),
                ('announcement', models.TextField(blank=True, null=True, verbose_name='餐厅公告')),
                ('service_charge_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='服务费率（百分比）')),
                ('is_open', models.BooleanField(default=True, verbose_name='是否营业中')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='起送金额')),
                ('table_count', models.IntegerField(default=0, verbose_name='餐桌数量')),
                ('avg_meal_time', models.IntegerField(default=60, verbose_name='平均用餐时间（分钟）')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '餐厅信息',
                'verbose_name_plural': '餐厅信息',
                'db_table': 'restaurant_info',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='配置ID')),
                ('config_key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('config_value', models.TextField(blank=True, null=True, verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='配置描述')),
                ('data_type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('boolean', '布尔值'), ('json', 'JSON')], default='string', max_length=20, verbose_name='数据类型')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否为公开配置')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_configs',
                'indexes': [models.Index(fields=['config_key'], name='idx_systemconfigs_key'), models.Index(fields=['is_public'], name='idx_systemconfigs_public')],
            },
        ),
    ]
