# Generated by Django 5.2 on 2025-06-07 07:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='分类ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='分类图片URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '菜品分类',
                'verbose_name_plural': '菜品分类',
                'db_table': 'categories',
                'ordering': ['-sort_order', 'id'],
                'indexes': [models.Index(fields=['-sort_order'], name='idx_categories_sort'), models.Index(fields=['is_active'], name='idx_categories_active')],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='菜品ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜品名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='菜品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='价格')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='菜品主图URL')),
                ('image_urls', models.JSONField(blank=True, null=True, verbose_name='菜品多图URLs')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('sales_count', models.IntegerField(default=0, verbose_name='销售数量')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否推荐菜品')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='菜品标签')),
                ('nutritional_info', models.JSONField(blank=True, null=True, verbose_name='营养信息')),
                ('spicy_level', models.SmallIntegerField(choices=[(0, '不辣'), (1, '微辣'), (2, '中辣'), (3, '重辣')], default=0, verbose_name='辣度等级')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dishes', to='dishes.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
                'db_table': 'dishes',
                'ordering': ['-sort_order', '-sales_count', 'id'],
                'indexes': [models.Index(fields=['category'], name='idx_dishes_category'), models.Index(fields=['is_active'], name='idx_dishes_active'), models.Index(fields=['is_recommended'], name='idx_dishes_recommended'), models.Index(fields=['price'], name='idx_dishes_price'), models.Index(fields=['-sales_count'], name='idx_dishes_sales'), models.Index(fields=['-sort_order'], name='idx_dishes_sort')],
            },
        ),
    ]
