# Generated by Django 5.2 on 2025-06-07 07:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='优惠券ID')),
                ('name', models.CharField(max_length=100, verbose_name='优惠券名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='优惠券代码')),
                ('type', models.CharField(choices=[('fixed_amount', '固定金额'), ('percentage', '百分比折扣'), ('free_shipping', '免配送费')], max_length=20, verbose_name='优惠券类型')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='优惠值')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='最小订单金额')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大优惠金额')),
                ('total_quantity', models.IntegerField(verbose_name='发放总数量')),
                ('used_quantity', models.IntegerField(default=0, verbose_name='已使用数量')),
                ('per_user_limit', models.IntegerField(default=1, verbose_name='每用户限用次数')),
                ('start_time', models.DateTimeField(verbose_name='有效期开始时间')),
                ('end_time', models.DateTimeField(verbose_name='有效期结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, null=True, verbose_name='使用说明')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'db_table': 'coupons',
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['code'], name='idx_coupons_code'), models.Index(fields=['type'], name='idx_coupons_type'), models.Index(fields=['is_active'], name='idx_coupons_active'), models.Index(fields=['start_time', 'end_time'], name='idx_coupons_time_range')],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期')], default='unused', max_length=20, verbose_name='使用状态')),
                ('received_time', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('used_time', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='coupons.coupon', verbose_name='优惠券')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'db_table': 'user_coupons',
            },
        ),
    ]
