# Generated by Django 5.2 on 2025-06-07 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['user'], name='idx_usercoupons_user'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['coupon'], name='idx_usercoupons_coupon'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['status'], name='idx_usercoupons_status'),
        ),
        migrations.AddConstraint(
            model_name='usercoupon',
            constraint=models.UniqueConstraint(fields=('user', 'coupon'), name='uk_user_coupon'),
        ),
    ]
