# Generated by Django 5.2 on 2025-06-07 07:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='支付记录ID')),
                ('payment_no', models.CharField(max_length=64, unique=True, verbose_name='支付流水号')),
                ('payment_method', models.CharField(choices=[('wechat_pay', '微信支付'), ('alipay', '支付宝'), ('cash', '现金支付')], max_length=20, verbose_name='支付方式')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='支付金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('success', '支付成功'), ('failed', '支付失败'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='支付状态')),
                ('third_party_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='第三方交易号')),
                ('prepay_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='预支付交易会话标识')),
                ('notify_data', models.JSONField(blank=True, null=True, verbose_name='支付回调通知数据')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='退款金额')),
                ('refund_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='退款原因')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_time', models.DateTimeField(blank=True, null=True, verbose_name='支付完成时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payments',
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['order'], name='idx_payments_order'), models.Index(fields=['payment_no'], name='idx_payments_payment_no'), models.Index(fields=['third_party_transaction_id'], name='idx_payments_third_party_id'), models.Index(fields=['status'], name='idx_payments_status'), models.Index(fields=['-created_time'], name='idx_payments_created_time')],
            },
        ),
    ]
