# Generated by Django 5.2 on 2025-06-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('openid', models.CharField(max_length=100, unique=True, verbose_name='微信openid')),
                ('union_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信unionid')),
                ('nickname', models.CharField(default='微信用户', max_length=100, verbose_name='微信昵称')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='微信头像URL')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('gender', models.SmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('is_active', models.BooleanField(default=True, verbose_name='账号是否激活')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'indexes': [models.Index(fields=['openid'], name='idx_users_openid'), models.Index(fields=['phone'], name='idx_users_phone'), models.Index(fields=['created_time'], name='idx_users_created_time')],
            },
        ),
    ]
