# Generated by Django 5.2 on 2025-06-07 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='反馈ID')),
                ('type', models.CharField(choices=[('suggestion', '建议'), ('complaint', '投诉'), ('bug_report', '问题反馈'), ('feature_request', '功能请求'), ('other', '其他')], default='suggestion', max_length=20, verbose_name='反馈类型')),
                ('title', models.CharField(max_length=200, verbose_name='反馈标题')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='反馈图片URLs')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='处理状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('admin_reply', models.TextField(blank=True, null=True, verbose_name='管理员回复')),
                ('reply_time', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='标签')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
                'db_table': 'feedbacks',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='评价ID')),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('content', models.TextField(blank=True, null=True, verbose_name='评价内容')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='评价图片URLs')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名评价')),
                ('reply_content', models.TextField(blank=True, null=True, verbose_name='商家回复内容')),
                ('reply_time', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='有用数量')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评价',
                'verbose_name_plural': '评价',
                'db_table': 'reviews',
                'ordering': ['-created_time'],
            },
        ),
    ]
