# Generated by Django 5.2 on 2025-06-07 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        ('orders', '0002_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='处理的管理员'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='反馈用户'),
        ),
        migrations.AddField(
            model_name='review',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dishes.dish', verbose_name='关联菜品'),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价用户'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['user'], name='idx_feedbacks_user'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['type'], name='idx_feedbacks_type'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status'], name='idx_feedbacks_status'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['priority'], name='idx_feedbacks_priority'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['admin'], name='idx_feedbacks_admin'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_time'], name='idx_feedbacks_created_time'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='idx_reviews_user'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order'], name='idx_reviews_order'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['dish'], name='idx_reviews_dish'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='idx_reviews_rating'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_visible'], name='idx_reviews_visible'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_time'], name='idx_reviews_created_time'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('order__isnull', False), ('dish__isnull', False), _connector='OR'), name='chk_review_target'),
        ),
    ]
